module GlobalConstants
  USER_DOES_NOT_EXIST = -1

  USER_ALREADY_IN_STUDYGROUP = -2
  STUDYGROUP_DOES_NOT_EXIST = -3

  USER_ALREADY_ENROLLED = -4
  USER_NOT_ALREADY_ENROLLED = -5
  COURSE_NONEXISTENT = -6
end