module GlobalConstants
  SUCCESS = 1

  USER_DOES_NOT_EXIST = -1
  USER_ALREADY_IN_STUDYGROUP = -2
  STUDYGROUP_DOES_NOT_EXIST = -3
  USER_NOT_STUDYGROUP_OWNER = -4

  USER_ALREADY_ENROLLED = -5
  USER_NOT_ALREADY_ENROLLED = -6
  COURSE_NONEXISTENT = -7
  USER_NOT_IN_STUDYGROUP = -8

  INVALID_STUDYGROUP = -9

  USER_NOT_INVITED = -10
end